(function(){
  let history=[];
  const ENDPOINT=()=>window.MEU_INGLES_AI_ENDPOINT||'';
  function s(){try{return typeof state!=='undefined'?state:null}catch(e){return null}}
  function saveSafe(){try{if(typeof save==='function')save()}catch(e){}}
  function mode(){const x=s();return x&&x.teacher?x.teacher:'media'}
  function level(){const x=s();return x&&x.level?x.level:'A1'}
  function modeLabel(){return mode()==='pesada'?'Hard 18+':mode()==='media'?'Doideira':'Tranquilo'}
  function faceMarkup(){return '<div class="coachHalo"></div><div class="coachShell"><div class="coachEyes"><span></span><span></span></div><div class="coachMouth"><i></i><i></i><i></i><i></i><i></i></div></div>'}
  function paintOrb(el,kind){if(!el)return;el.classList.remove('listening','thinking','speaking','hard','doida');if(mode()==='pesada')el.classList.add('hard');else if(mode()==='media')el.classList.add('doida');if(kind&&kind!=='idle')el.classList.add(kind)}
  function allOrbs(kind){document.querySelectorAll('.coachOrb').forEach(x=>paintOrb(x,kind))}
  function bestPtVoice(){const vs=(speechSynthesis.getVoices()||[]).filter(v=>/^pt(-|_)?br/i.test(v.lang));const score=v=>/google/i.test(v.name)?5:/microsoft/i.test(v.name)?4:/samsung/i.test(v.name)?3:1;return vs.sort((a,b)=>score(b)-score(a))[0]||null}
  function speakPt(text,done){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.98;u.pitch=1;const v=bestPtVoice();if(v)u.voice=v;u.onstart=()=>allOrbs('speaking');u.onend=()=>{allOrbs('idle');if(done)done()};speechSynthesis.speak(u)}catch(e){if(done)done()}}
  function speakBoth(pt,en){speakPt(pt,()=>{if(!en)return;try{if(typeof speakEn==='function')speakEn(en);else if(typeof speak==='function')speak(en)}catch(e){}})}
  function setMode(m){const st=s();if(!st)return;st.teacher=m;saveSafe();renderModeButtons();allOrbs('idle');const msg=m==='leve'?'Modo tranquilo. Eu vou corrigir com calma.':m==='media'?'Modo doideira ativado. Agora tem resenha, mas continua sendo aula.':'Hard dezoito mais ativado. Errou muito, a professora vai perder a paciência.';speakPt(msg)}
  window.coachSetMode=setMode;
  function renderModeButtons(){document.querySelectorAll('[data-coach-mode]').forEach(b=>b.classList.toggle('active',b.dataset.coachMode===mode()))}
  function levelChips(){return ['A1','A2','B1','B2','C1','C2'].map(x=>`<span class="coachLevelChip ${x===level()?'current':''}">${x}</span>`).join('')}
  function injectHome(){
    const home=document.getElementById('home'),hero=home&&home.querySelector('.hero');if(!home||!hero)return;
    const old=document.getElementById('coachHome');if(old)old.remove();
    const block=document.createElement('section');block.id='coachHome';block.className='coachHome';
    block.innerHTML=`<div class="coachHead"><div><h2>Professor IA</h2><p>Ele acompanha suas aulas e reage de acordo com o estilo escolhido.</p></div><span id="coachBackend" class="coachOnline">verificando IA…</span></div><div class="coachStage"><div id="coachHomeOrb" class="coachOrb">${faceMarkup()}</div><div class="coachCopy"><h3>Aprender primeiro. Zoar depois.</h3><p>Escolha seu nível no curso. A personalidade muda a forma da correção, não a dificuldade do inglês.</p><div class="coachLevelStrip">${levelChips()}</div></div></div><div class="coachModeTitle">Como o professor vai reagir nas tarefas</div><div class="coachModes"><button data-coach-mode="leve" class="coachMode" onclick="coachSetMode('leve')">🙂 Tranquilo</button><button data-coach-mode="media" class="coachMode" onclick="coachSetMode('media')">🤪 Doideira</button><button data-coach-mode="pesada" class="coachMode hard" onclick="coachSetMode('pesada')">🔥 Hard 18+</button></div><div class="coachActions"><button class="coachPrimary" onclick="openScreen('course')">📚 Continuar curso</button><button class="coachSecondary" onclick="openScreen('chat')">🗣️ Conversa livre</button></div><div class="coachNote">O modo de personalidade vale também para as correções das aulas A1 até C2.</div>`;
    hero.insertAdjacentElement('afterend',block);renderModeButtons();paintOrb(document.getElementById('coachHomeOrb'),'idle');checkBackend();
  }
  async function checkBackend(){const badge=document.getElementById('coachBackend'),live=document.getElementById('liveAiState');if(!ENDPOINT()){if(badge){badge.className='coachOnline bad';badge.textContent='IA não configurada'}return false}try{const r=await fetch(ENDPOINT(),{method:'GET',cache:'no-store'});const d=await r.json();const ok=r.ok&&d.ok&&d.key_configured;if(badge){badge.className='coachOnline '+(ok?'ok':'bad');badge.textContent=ok?'Groq IA online':'IA sem chave'}if(live){live.className='aiState '+(ok?'connected':'pending');live.textContent=ok?'🧠 GroqCloud conectada. Respostas inteligentes ativas.':'⚠️ Backend da IA ainda não está pronto.'}return ok}catch(e){if(badge){badge.className='coachOnline bad';badge.textContent='IA offline'}if(live){live.className='aiState pending';live.textContent='⚠️ Não consegui alcançar o servidor da IA.'}return false}}
  async function ask(payload){const endpoint=ENDPOINT();if(!endpoint)throw new Error('endpoint_missing');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.error||('http_'+r.status));return d}
  function streakKey(target){return level()+'|'+String(target||'').toLowerCase()}
  function updateStreak(target,passed){const st=s();if(!st)return 0;st.aiErrorStreak=st.aiErrorStreak||{};const k=streakKey(target);st.aiErrorStreak[k]=passed?0:(st.aiErrorStreak[k]||0)+1;saveSafe();return st.aiErrorStreak[k]}
  function feedbackHtml(box,sc,heard,passed,text,en,loading){if(!box)return;box.className='result show '+(passed?'good':'bad');box.innerHTML=`<b>${sc}% de compatibilidade</b><p>Eu ouvi: “${heard}”</p><div class="coachFeedback ${passed?'good':'bad'} ${loading?'coachLoading':''}"><span class="miniOrb"></span><div class="coachText">${text||'Analisando sua tentativa…'}${en?`<span class="coachEnglish">${en}</span>`:''}</div></div><small class="muted">A porcentagem mede o texto reconhecido pelo aparelho; não é uma nota exata da pronúncia.</small>`}
  function patchCourse(){
    window.practiceLessonV6=async function(btn,index){
      const st=s(),lesson=window.L_V6&&L_V6[st.level]&&L_V6[st.level][index];if(!lesson)return;
      let r=null;try{r=await prep()}catch(e){}if(!r)return;const box=btn.closest('.lesson').querySelector('.result');
      try{toast('Estou ouvindo...')}catch(e){};r.onstart=()=>{try{setMicTop('listening')}catch(e){};allOrbs('listening')};
      r.onresult=async e=>{const best=bestHeard(e.results[0],lesson[1]),heard=best.heard,sc=best.sc,passed=sc>=passLine();try{saveError(sc,heard,lesson[1])}catch(err){};const streak=updateStreak(lesson[1],passed);feedbackHtml(box,sc,heard,passed,'A professora está analisando sua tentativa…','',true);allOrbs('thinking');
        try{const d=await ask({mode:'lesson_feedback',message:heard,heard,target:lesson[1],lesson:lesson[0],score:sc,passed,error_streak:streak,level:st.level,personality:st.teacher,scenario:'Aula'});feedbackHtml(box,sc,heard,passed,d.reply_pt,d.reply_en,false);speakBoth(d.reply_pt,d.reply_en)}catch(err){console.warn(err);const pt=passed?'O reconhecimento entendeu a frase corretamente. A inteligência está offline agora, então vou só marcar a tentativa como certa.':`A inteligência está offline agora. Eu ouvi “${heard}”. Tente novamente: ${lesson[1]}`;feedbackHtml(box,sc,heard,passed,pt,passed?'':lesson[1],false);const warn=document.getElementById('coachBackend');if(warn){warn.className='coachOnline bad';warn.textContent='IA offline'};speakBoth(pt,passed?'':lesson[1])}
      };
      r.onerror=()=>{allOrbs('idle');try{setMicTop('bad');toast('Não entendi. Tente novamente.')}catch(e){};speakPt(mode()==='pesada'?'Não ouvi direito, Cláudio. Fala essa porra de novo.':mode()==='media'?'Não peguei, Cláudio. Manda de novo.':'Não consegui ouvir bem. Tente novamente.')};r.onend=()=>{try{setMicTop(micReady?'ready':'')}catch(e){}};try{r.start()}catch(e){allOrbs('idle')}
    };
  }
  function patchChat(){
    const chat=document.getElementById('chat');if(!chat)return;const m=document.getElementById('liveMascot');if(m){m.classList.add('proMascot');m.innerHTML='<div class="mascotMouth"></div>'}
    const controls=chat.querySelector('.liveControls');if(controls)controls.style.display='none';
    window.liveVoiceChat=async function(){let r=null;try{r=await prep()}catch(e){}if(!r)return;const btn=document.getElementById('liveMicBtn'),heardEl=document.getElementById('liveLastHeard'),replyEl=document.getElementById('liveLastReply'),hint=document.getElementById('liveHint');if(btn)btn.classList.add('listening');if(hint)hint.textContent='Pode falar. A IA vai responder ao que você disser.';allOrbs('listening');try{if(typeof liveSetMascotState==='function')liveSetMascotState('listening')}catch(e){};
      r.onresult=async e=>{const text=e.results[0][0].transcript;if(heardEl)heardEl.textContent=text;if(btn)btn.classList.remove('listening');if(hint)hint.textContent='Pensando na sua resposta…';allOrbs('thinking');try{if(typeof liveSetMascotState==='function')liveSetMascotState('thinking')}catch(e){};
        try{const st=s(),d=await ask({mode:'conversation',message:text,level:st.level,personality:st.teacher,scenario:st.scenario||'Livre',history:history.slice(-8)});history.push({role:'user',content:text},{role:'assistant',content:(d.reply_pt||'')+' '+(d.reply_en||'')});if(replyEl)replyEl.textContent=[d.reply_pt,d.reply_en].filter(Boolean).join(' • ');if(hint)hint.textContent='Resposta da IA';speakBoth(d.reply_pt,d.reply_en)}catch(err){console.warn(err);if(replyEl)replyEl.textContent='A IA não respondeu. Não vou fingir que entendi sua resposta.';if(hint)hint.textContent='Servidor da IA indisponível';const live=document.getElementById('liveAiState');if(live){live.className='aiState pending';live.textContent='⚠️ GroqCloud não respondeu. Tente novamente em alguns segundos.'};speakPt('A inteligência não respondeu agora. Tenta de novo em alguns segundos.')}
      };
      r.onerror=()=>{if(btn)btn.classList.remove('listening');allOrbs('idle');try{if(typeof liveSetMascotState==='function')liveSetMascotState('idle')}catch(e){};try{toast('Não entendi. Tente novamente.')}catch(e){}};r.onend=()=>{if(btn)btn.classList.remove('listening')};try{r.start()}catch(e){allOrbs('idle')}
    };
  }
  function patchLiveAppearance(){const old=document.getElementById('liveAiState');if(old){old.textContent='🧠 Verificando conexão com a GroqCloud…';old.className='aiState pending'};const lm=document.getElementById('liveMascot');if(lm){lm.classList.add('proMascot')}checkBackend()}
  function wrapLevel(){if(window.__coachLevelWrapped)return;try{const old=window.setLevel;window.setLevel=function(l){const r=old.apply(this,arguments);setTimeout(()=>{injectHome();renderModeButtons()},30);return r};window.__coachLevelWrapped=true}catch(e){}}
  function init(){injectHome();patchCourse();patchChat();patchLiveAppearance();wrapLevel();renderModeButtons();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>{} }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,180));else setTimeout(init,180);
})();
