(function(){
  function faceMarkup(){return '<div class="coachHalo"></div><div class="coachShell"><div class="coachEyes"><span></span><span></span></div><div class="coachMouth"><i></i><i></i><i></i><i></i><i></i></div></div>'}
  function repairMascot(){const m=document.getElementById('liveMascot');if(!m)return;m.classList.add('coachOrb','liveCoachOrb');if(!m.querySelector('.coachShell'))m.innerHTML=faceMarkup();try{if(typeof liveSetMascotState==='function')liveSetMascotState('idle')}catch(e){}}
  async function speakWord(en){en=String(en||'').trim();if(!en)return;try{if(window.GEMINI_TTS){const ok=await GEMINI_TTS.speak(en,'en-US',{style:'Natural English teaching voice. Pronounce the word clearly once.'});if(ok)return}}catch(e){}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(en);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}catch(e){}}
  document.addEventListener('click',e=>{const row=e.target.closest&&e.target.closest('.vocabRow');if(!row)return;const word=(row.querySelector('b')?.textContent||'').trim();if(!word)return;row.classList.add('vocabInteractive','playing');speakWord(word).finally(()=>setTimeout(()=>row.classList.remove('playing'),250))});
  document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const row=e.target.closest&&e.target.closest('.vocabRow');if(!row)return;e.preventDefault();row.click()});
  function prepareVocab(){document.querySelectorAll('.vocabRow').forEach(row=>{row.classList.add('vocabInteractive');row.setAttribute('role','button');row.setAttribute('tabindex','0')});document.querySelectorAll('.lessonSection').forEach(sec=>{const h=sec.querySelector('h3');if(!h||!h.textContent.includes('Vocabulário')||sec.querySelector('.vocabHint'))return;const hint=document.createElement('div');hint.className='vocabHint';hint.textContent='Toque em uma palavra para ouvir a pronúncia.';h.insertAdjacentElement('afterend',hint)})}
  async function refreshAiStatus(){const badge=document.getElementById('coachBackend'),live=document.getElementById('liveAiState'),endpoint=window.MEU_INGLES_AI_ENDPOINT||'https://meu-ingles-claudio.netlify.app/api/groq-chat';try{const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json(),ok=!!(r.ok&&d.ok&&d.key_configured);if(badge){badge.className='coachOnline '+(ok?'ok':'bad');badge.textContent=ok?'IA online':'IA indisponível'}if(live){live.className='aiState '+(ok?'connected':'pending');live.textContent=ok?'🧠 IA conectada · Groq/Gemini':'⚠️ IA indisponível agora'}}catch(e){if(badge){badge.className='coachOnline bad';badge.textContent='IA offline'}if(live){live.className='aiState pending';live.textContent='⚠️ Servidor da IA não respondeu'}}}
  function afterScreen(){setTimeout(()=>{repairMascot();prepareVocab();refreshAiStatus()},80)}
  function init(){repairMascot();prepareVocab();refreshAiStatus();try{const old=window.openScreen;if(typeof old==='function'&&!window.__stableOpenScreen){window.openScreen=function(){const r=old.apply(this,arguments);afterScreen();return r};window.__stableOpenScreen=true}}catch(e){};document.addEventListener('click',e=>{if(e.target.closest&&e.target.closest('[onclick*="openCourseLessonV12"],[onclick*="openCourseModuleV12"]'))setTimeout(prepareVocab,500)},{capture:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,150));else setTimeout(init,150);
})();
