(()=>{
'use strict';
const STORE='meuInglesMethodsV1';
const SESSION='meuInglesMethodSessionV1';
const THEMES=[
 {id:'familia',title:'Família',emoji:'👨‍👩‍👧‍👦',cls:'theme-family',desc:'Pais, irmãos, avós, tios e relações familiares.',stages:['Vocabulário da família','Quem é quem','Minha família','Idades e nomes','Perguntas simples','Descrição de pessoas','Rotina em família','Possessivos','Árvore genealógica','Conversação sobre família'],examples:[['This is my mother.','Esta é minha mãe.'],['I have one brother.','Eu tenho um irmão.'],['My grandmother is kind.','Minha avó é gentil.'],['Do you have any sisters?','Você tem irmãs?'],['My uncle lives in Rio.','Meu tio mora no Rio.'],['Her father is a teacher.','O pai dela é professor.']]},
 {id:'pedindo-comida',title:'Pedindo comida',emoji:'🍕',cls:'theme-food',desc:'Cardápio, pedidos, bebidas, preferências e conta.',stages:['Comidas básicas','Bebidas','I would like…','No cardápio','Fazendo o pedido','Preferências','Perguntas ao garçom','Problemas no pedido','Pedindo a conta','Simulação completa'],examples:[['I would like a hamburger, please.','Eu gostaria de um hambúrguer, por favor.'],['Can I have some water?','Posso pedir água?'],['What do you recommend?','O que você recomenda?'],['No onions, please.','Sem cebola, por favor.'],['Can I have the bill, please?','Pode trazer a conta, por favor?'],['Is this spicy?','Isso é apimentado?']]},
 {id:'viagem',title:'Viagem',emoji:'🧳',cls:'theme-travel',desc:'Planejamento, passeio, informações e situações de viagem.',stages:['Planejando a viagem','Destinos','Datas e horários','Bagagem','Chegando ao destino','Perguntando informações','Passeios','Problemas comuns','Mudando planos','Conversa de viagem'],examples:[['I am traveling tomorrow.','Eu vou viajar amanhã.'],['Where is the city center?','Onde fica o centro da cidade?'],['I have two bags.','Eu tenho duas malas.'],['How long does it take?','Quanto tempo demora?'],['I want to visit the museum.','Eu quero visitar o museu.'],['Can you help me with directions?','Você pode me ajudar com as direções?']]},
 {id:'hotel',title:'Hotel',emoji:'🏨',cls:'theme-hotel',desc:'Reserva, check-in, quarto, serviços e check-out.',stages:['Tipos de quarto','Fazendo reserva','Datas da estadia','Check-in','No quarto','Serviços do hotel','Pedindo ajuda','Problemas no quarto','Check-out','Situação completa'],examples:[['I have a reservation.','Eu tenho uma reserva.'],['I need a double room.','Eu preciso de um quarto de casal.'],['What time is breakfast?','Que horas é o café da manhã?'],['The air conditioner is not working.','O ar-condicionado não está funcionando.'],['Can I have another towel?','Posso pedir outra toalha?'],['I would like to check out.','Eu gostaria de fazer o check-out.']]},
 {id:'aeroporto',title:'Aeroporto',emoji:'✈️',cls:'theme-airport',desc:'Check-in, portão, bagagem, imigração e voo.',stages:['No aeroporto','Check-in','Documentos','Bagagem','Portão de embarque','Horários de voo','Segurança','Imigração','Atrasos e mudanças','Embarque completo'],examples:[['Where is the check-in counter?','Onde fica o balcão de check-in?'],['Here is my passport.','Aqui está meu passaporte.'],['Which gate is it?','Qual é o portão?'],['My flight is delayed.','Meu voo está atrasado.'],['I only have carry-on luggage.','Eu só tenho bagagem de mão.'],['What time does boarding start?','Que horas começa o embarque?']]},
 {id:'transporte',title:'Transportes',emoji:'🚌',cls:'theme-transport',desc:'Ônibus, metrô, táxi, aplicativo e direções.',stages:['Meios de transporte','Pontos e estações','Comprando passagem','Perguntando direção','Táxi e aplicativo','Metrô','Ônibus','Tempo de trajeto','Trocas e conexões','Rota completa'],examples:[['Where is the bus stop?','Onde fica o ponto de ônibus?'],['How much is the ticket?','Quanto custa a passagem?'],['I need a taxi.','Eu preciso de um táxi.'],['Does this bus go downtown?','Este ônibus vai para o centro?'],['Which line should I take?','Qual linha eu devo pegar?'],['Please stop here.','Por favor, pare aqui.']]},
 {id:'trabalho',title:'Trabalho',emoji:'💼',cls:'theme-work',desc:'Profissões, rotina, colegas, tarefas e reuniões.',stages:['Profissões','Local de trabalho','Rotina profissional','Horários','Tarefas','Colegas','Pedidos e ajuda','Reuniões','Problemas no trabalho','Conversa profissional'],examples:[['I work in the morning.','Eu trabalho de manhã.'],['She is my manager.','Ela é minha gerente.'],['I have a meeting today.','Eu tenho uma reunião hoje.'],['Can you help me with this task?','Você pode me ajudar com esta tarefa?'],['I finish work at six.','Eu termino o trabalho às seis.'],['What do you do for work?','Com o que você trabalha?']]},
 {id:'compras',title:'Compras',emoji:'🛍️',cls:'theme-shopping',desc:'Preços, tamanhos, cores, pagamento e trocas.',stages:['Lojas e produtos','Preços','Tamanhos','Cores','Experimentando','Comparando produtos','Pagamento','Descontos','Trocas','Compra completa'],examples:[['How much is this?','Quanto custa isto?'],['Do you have a larger size?','Você tem um tamanho maior?'],['I like the blue one.','Eu gosto do azul.'],['Can I try this on?','Posso experimentar isto?'],['Can I pay by card?','Posso pagar com cartão?'],['I would like to exchange this.','Eu gostaria de trocar isto.']]},
 {id:'saude',title:'Saúde',emoji:'🩺',cls:'theme-health',desc:'Sintomas simples, farmácia, consulta e bem-estar.',stages:['Partes do corpo','Como você se sente','Sintomas comuns','Na farmácia','Na consulta','Dor e intensidade','Hábitos saudáveis','Orientações simples','Marcando consulta','Conversa completa'],examples:[['I have a headache.','Eu estou com dor de cabeça.'],['My throat hurts.','Minha garganta dói.'],['I need a pharmacy.','Eu preciso de uma farmácia.'],['How long have you felt this way?','Há quanto tempo você se sente assim?'],['I feel better today.','Eu me sinto melhor hoje.'],['I need to make an appointment.','Eu preciso marcar uma consulta.']]},
 {id:'casa',title:'Casa e rotina',emoji:'🏠',cls:'theme-home',desc:'Cômodos, objetos, tarefas e rotina em casa.',stages:['Cômodos','Objetos da casa','Onde está?','Minha casa','Tarefas domésticas','Rotina da manhã','Rotina da noite','Convidando alguém','Problemas em casa','Conversa completa'],examples:[['The kitchen is small.','A cozinha é pequena.'],['My keys are on the table.','Minhas chaves estão sobre a mesa.'],['I clean the house on Saturday.','Eu limpo a casa no sábado.'],['There are two bedrooms.','Há dois quartos.'],['Please sit on the sofa.','Por favor, sente-se no sofá.'],['I make coffee every morning.','Eu faço café toda manhã.']]}
];
let screen=null,currentView='themes',activeTheme=null,activeVisualLesson=1,robotSheet=null,robotSheetMode='themes',methodSession=loadSession();
const previousFetch=window.fetch.bind(window);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function themeById(id){return THEMES.find(t=>t.id===id)||THEMES[0]}
function lessonTitle(theme,n){const idx=Math.max(0,Math.min(39,Number(n||1)-1));const stage=theme.stages[Math.floor(idx/4)]||theme.stages[0];return `${stage} · parte ${(idx%4)+1}`}
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch{return {}}}
function save(data){try{localStorage.setItem(STORE,JSON.stringify(data))}catch{}}
function loadSession(){try{return JSON.parse(sessionStorage.getItem(SESSION)||'null')}catch{return null}}
function saveSession(){try{methodSession?sessionStorage.setItem(SESSION,JSON.stringify(methodSession)):sessionStorage.removeItem(SESSION)}catch{}}
function dataFor(id){const s=load();s.themes=s.themes||{};s.themes[id]=s.themes[id]||{completed:[],current:1};return {root:s,item:s.themes[id]}}
function completedCount(id){return new Set(dataFor(id).item.completed||[]).size}
function currentLesson(id){const n=Number(dataFor(id).item.current||1);return Math.max(1,Math.min(40,n))}
function setCurrent(id,n){const {root,item}=dataFor(id);item.current=Math.max(1,Math.min(40,Number(n)||1));root.lastTheme=id;root.lastLesson=item.current;save(root)}
function completeLesson(id,n){const {root,item}=dataFor(id);const set=new Set(item.completed||[]);set.add(Number(n));item.completed=[...set].sort((a,b)=>a-b);item.current=Math.min(40,Number(n)+1);root.lastTheme=id;root.lastLesson=item.current;save(root);refreshAll()}
function percent(id){return Math.round((completedCount(id)/40)*100)}
function renderHomeCard(){const home=document.querySelector('#home');const all=home?.querySelector('.allCoursesCard');if(!all)return;if(home.querySelector('.methodsHomeCard'))return;const d=document.createElement('div');d.className='methodsHomeCard';d.setAttribute('role','button');d.tabIndex=0;d.innerHTML='<div class="methodsHomeIcon">🧭</div><div class="methodsHomeCopy"><small>ESTUDO POR ASSUNTO</small><b>Métodos</b><span>Família, viagens, comida, hotel e muito mais.</span></div><div class="methodsHomeArrow">›</div>';d.addEventListener('click',openMethods);d.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openMethods()}});all.insertAdjacentElement('afterend',d)}
function decorateRobot(){const card=document.querySelector('#home .professorPanel.homeTalkCard');if(!card)return;const stage=card.querySelector('.homeRobotStage');if(!stage)return;if(!card.querySelector('.robotMethodsEntry')){const b=document.createElement('button');b.type='button';b.className='robotMethodsEntry';b.innerHTML='<span class="rmIcon">🧭</span><span class="rmCopy"><b>Métodos</b><small>Escolha um tema e uma aula particular</small></span><span class="rmArrow">›</span>';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openRobotThemes()});stage.insertAdjacentElement('afterend',b)}
 const free=card.querySelector('.homeConversationChoice[data-v26mode="free"]');if(free){const b=free.querySelector('b'),s=free.querySelector('small');if(b)b.textContent='Conversa livre';if(s)s.textContent='Escolha qualquer assunto e pratique inglês'}
 if(!card.classList.contains('chat-open')&&typeof window.chooseV26Mode==='function'){try{window.chooseV26Mode('free')}catch{}}
 ensureRobotSheet(card);decorateMethodPill();}
function ensureRobotSheet(card){if(robotSheet&&robotSheet.isConnected)return;robotSheet=document.createElement('div');robotSheet.className='robotMethodsSheet';robotSheet.innerHTML='<div class="robotMethodsSheetHead"><button type="button" class="robotSheetBack">‹</button><h3>Métodos</h3></div><div class="robotMethodsSheetBody"></div>';card.appendChild(robotSheet);robotSheet.querySelector('.robotSheetBack').addEventListener('click',()=>{if(robotSheetMode==='lessons'){robotSheetMode='themes';renderRobotThemes()}else closeRobotSheet()})}
function openRobotThemes(){robotSheetMode='themes';renderRobotThemes();robotSheet?.classList.add('open')}
function closeRobotSheet(){robotSheet?.classList.remove('open')}
function renderRobotThemes(){if(!robotSheet)return;robotSheet.querySelector('h3').textContent='Escolha um tema';const body=robotSheet.querySelector('.robotMethodsSheetBody');body.innerHTML=THEMES.map(t=>`<button class="robotThemePick" data-theme="${t.id}"><span class="emoji">${t.emoji}</span><span><b>${esc(t.title)}</b><small>${completedCount(t.id)}/40 aulas concluídas</small></span><span class="go">›</span></button>`).join('');body.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>renderRobotLessons(b.dataset.theme)))}
function renderRobotLessons(id){const t=themeById(id);robotSheetMode='lessons';robotSheet.querySelector('h3').textContent=t.title;const body=robotSheet.querySelector('.robotMethodsSheetBody');const current=currentLesson(id);const done=new Set(dataFor(id).item.completed||[]);body.innerHTML=`<div class="robotLessonQuickActions"><button class="continue">▶ Continuar da aula ${current}</button><button class="start">Do início</button><button class="random">Aleatória</button></div><div class="robotLessonNums">${Array.from({length:40},(_,i)=>{const n=i+1;return `<button data-lesson="${n}" class="${done.has(n)?'done ':''}${current===n?'current':''}">${n}</button>`}).join('')}</div>`;body.querySelector('.continue').onclick=()=>startMethodWithRobot(id,current);body.querySelector('.start').onclick=()=>startMethodWithRobot(id,1);body.querySelector('.random').onclick=()=>startMethodWithRobot(id,1+Math.floor(Math.random()*40));body.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>startMethodWithRobot(id,Number(b.dataset.lesson)))}
function createScreen(){if(screen)return;screen=document.createElement('div');screen.className='methodsScreen';screen.innerHTML='<div class="methodsScreenInner"><div class="methodsTopbar"><button class="methodsBack">‹</button><h2>Métodos</h2><span class="methodsTopMeta"></span></div><div class="methodsContent"></div></div>';document.body.appendChild(screen);screen.querySelector('.methodsBack').addEventListener('click',methodsBack)}
function openMethods(){createScreen();currentView='themes';activeTheme=null;renderMethodsThemes();screen.classList.add('open');document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden'}
function closeMethods(){screen?.classList.remove('open');document.documentElement.style.overflow='';document.body.style.overflow=''}
function methodsBack(){if(currentView==='lesson'){currentView='theme';renderThemeLessons(activeTheme);return}if(currentView==='theme'){currentView='themes';activeTheme=null;renderMethodsThemes();return}closeMethods()}
function renderMethodsThemes(){createScreen();screen.querySelector('.methodsTopbar h2').textContent='Métodos';screen.querySelector('.methodsTopMeta').textContent='40 aulas por tema';const content=screen.querySelector('.methodsContent');content.innerHTML=`<div class="methodsHero"><h1>Aprenda por temas</h1><p>Escolha um assunto e avance no seu ritmo. O progresso daqui é o mesmo usado nas aulas particulares com o robozinho.</p></div><div class="methodsThemeList">${THEMES.map(t=>`<button class="methodsThemeCard ${t.cls}" data-theme="${t.id}"><h3>${esc(t.title)}</h3><span class="methodsThemeCount">${completedCount(t.id)}/40<small>aulas</small></span><span class="methodsThemeArt">${t.emoji}</span><span class="methodsThemeProgress"><i style="width:${percent(t.id)}%"></i></span></button>`).join('')}</div>`;content.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{activeTheme=b.dataset.theme;currentView='theme';renderThemeLessons(activeTheme)})}
function renderThemeLessons(id){createScreen();const t=themeById(id);activeTheme=id;currentView='theme';screen.querySelector('.methodsTopbar h2').textContent=t.title;screen.querySelector('.methodsTopMeta').textContent=`${completedCount(id)}/40`;const current=currentLesson(id);const done=new Set(dataFor(id).item.completed||[]);const content=screen.querySelector('.methodsContent');content.innerHTML=`<div class="methodsThemeHead"><h1>${t.emoji} ${esc(t.title)}</h1><p>${esc(t.desc)}</p></div><div class="methodsActionRow"><button class="primary continueTheme">▶ Continuar da aula ${current}</button><button class="startTheme">Começar do início</button><button class="randomTheme">Aula aleatória</button></div><div class="methodsLessonsGrid">${Array.from({length:40},(_,i)=>{const n=i+1;return `<button class="methodsLessonCard ${done.has(n)?'done':''}" data-lesson="${n}"><span class="methodsLessonNum">${done.has(n)?'✓':n}</span><span class="methodsLessonText"><b>${esc(lessonTitle(t,n))}</b><small>Aula ${n} de 40 · ${done.has(n)?'concluída':'pronta para estudar'}</small></span><span class="methodsLessonArrow">›</span></button>`}).join('')}</div>`;content.querySelector('.continueTheme').onclick=()=>openVisualLesson(id,current);content.querySelector('.startTheme').onclick=()=>openVisualLesson(id,1);content.querySelector('.randomTheme').onclick=()=>openVisualLesson(id,1+Math.floor(Math.random()*40));content.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openVisualLesson(id,Number(b.dataset.lesson)))}
function lessonExamples(t,n){const arr=t.examples||[];return Array.from({length:5},(_,i)=>arr[((n-1)*2+i)%arr.length])}
function openVisualLesson(id,n){const t=themeById(id);activeTheme=id;activeVisualLesson=n;currentView='lesson';setCurrent(id,n);screen.querySelector('.methodsTopbar h2').textContent=`${t.title} · Aula ${n}`;screen.querySelector('.methodsTopMeta').textContent=`${n}/40`;const content=screen.querySelector('.methodsContent');const rows=lessonExamples(t,n);content.innerHTML=`<div class="methodsVisualLesson"><div class="methodsVisualBanner"><small>AULA ${n} DE 40</small><h2>${esc(lessonTitle(t,n))}</h2><p>${esc(t.desc)}</p><div class="methodsVisualProgress"><i style="width:${Math.round(n/40*100)}%"></i></div></div><div class="methodsPhraseList">${rows.map((r,i)=>`<div class="methodsPhraseCard"><b>${esc(r[0])}</b><span>${esc(r[1])}</span><div class="methodsPhraseActions"><button data-speak="${i}">🔊 Ouvir</button></div></div>`).join('')}</div><div class="methodsLessonFooter"><button class="withRobot">🤖 Praticar com o robô</button><button class="completeLesson">✓ Concluir aula</button></div></div>`;content.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speakPhrase(rows[Number(b.dataset.speak)]?.[0]||''));content.querySelector('.withRobot').onclick=()=>{closeMethods();startMethodWithRobot(id,n)};content.querySelector('.completeLesson').onclick=()=>{completeLesson(id,n);if(n<40)openVisualLesson(id,n+1);else renderThemeLessons(id)}}
async function speakPhrase(text){if(!text)return;try{const st=JSON.parse(localStorage.getItem('meuInglesStableV2')||'{}');const voice=st.voice||'Aoede';if(window.geminiSpeak)await window.geminiSpeak(text,'en-US',voice)}catch{}}
async function startMethodWithRobot(id,n){const t=themeById(id);setCurrent(id,n);methodSession={themeId:id,lesson:n,title:t.title,lessonTitle:lessonTitle(t,n),turns:0,correct:0};saveSession();closeRobotSheet();closeMethods();try{window.stableShow?.('home')}catch{};await new Promise(r=>setTimeout(r,80));try{if(document.querySelector('#home .homeTalkCard.chat-open'))window.closeV26Conversation?.({preventDefault(){},stopPropagation(){}})}catch{};await new Promise(r=>setTimeout(r,100));try{window.chooseV26Mode?.('free')}catch{};let oldSpeak=window.geminiSpeak;try{if(oldSpeak)window.geminiSpeak=async()=>{};await window.startV26Conversation?.()}finally{if(oldSpeak)window.geminiSpeak=oldSpeak}await new Promise(r=>setTimeout(r,80));const input=document.querySelector('#homeChatInput');if(input){input.value=`${t.title}, aula ${n} de 40: ${lessonTitle(t,n)}`;window.v26Send?.()}decorateMethodPill()}
function decorateMethodPill(){if(!methodSession)return;const p=document.querySelector('#homeTopicPill');if(!p)return;const t=themeById(methodSession.themeId);p.textContent=`← ${t.title} · Aula ${methodSession.lesson}/40`;p.classList.add('methodSessionPill');p.onclick=e=>{e.preventDefault();e.stopPropagation();openRobotThemes();setTimeout(()=>renderRobotLessons(methodSession.themeId),20)}}
function refreshAll(){if(screen?.classList.contains('open')){if(currentView==='themes')renderMethodsThemes();else if(currentView==='theme')renderThemeLessons(activeTheme)}decorateRobot()}
function isChatUrl(url){return /\/api\/groq-chat(?:\?|$)/.test(String(url||''))}
window.fetch=function(input,init){let url='';try{url=typeof input==='string'||input instanceof URL?String(input):input?.url||''}catch{};if(!methodSession||!isChatUrl(url)||!init?.body)return previousFetch(input,init);let body;try{body=JSON.parse(init.body)}catch{return previousFetch(input,init)};const t=themeById(methodSession.themeId);body.conversation_mode='free';body.learning_topic=`${t.title} — aula ${methodSession.lesson} de 40: ${methodSession.lessonTitle}`;body.scenario=`MÉTODO TEMÁTICO. Aula particular de inglês sobre ${t.title}, aula ${methodSession.lesson} de 40 (${methodSession.lessonTitle}). Fique SOMENTE dentro deste tema e desta aula. Ensine progressivamente, faça uma pergunta curta por vez, corrija antes de avançar e use exemplos ligados a ${t.title}.`;body.method_theme=t.title;body.method_lesson=methodSession.lesson;const nextInit={...init,body:JSON.stringify(body)};const p=previousFetch(input,nextInit);p.then(res=>{try{res.clone().json().then(d=>{if(!methodSession)return;methodSession.turns=(methodSession.turns||0)+1;if(d?.verdict==='correct')methodSession.correct=(methodSession.correct||0)+1;saveSession();if(methodSession.correct>=4||methodSession.turns>=8){completeLesson(methodSession.themeId,methodSession.lesson);methodSession.lesson=Math.min(40,methodSession.lesson+1);methodSession.lessonTitle=lessonTitle(themeById(methodSession.themeId),methodSession.lesson);methodSession.turns=0;methodSession.correct=0;saveSession();setTimeout(decorateMethodPill,30)}}).catch(()=>{})}catch{}}).catch(()=>{});return p}
function observe(){const root=document.querySelector('#home');if(root)new MutationObserver(()=>{renderHomeCard();decorateRobot();decorateMethodPill()}).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('storage',e=>{if(e.key===STORE)refreshAll()})}
function init(){renderHomeCard();decorateRobot();decorateMethodPill();observe();window.openMethodsV39=openMethods;window.openRobotMethodsV39=openRobotThemes;window.startMethodWithRobotV39=startMethodWithRobot}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,350));else setTimeout(init,350);
})();
