(()=>{
'use strict';
const API_BASE=location.hostname.endsWith('github.io')?'https://meu-ingles-claudio.netlify.app':'';
const CHAT=API_BASE+'/api/groq-chat', COURSE=API_BASE+'/api/course-lesson', TTS=API_BASE+'/api/gemini-tts';
const LEVELS={A1:'Iniciante',A2:'Básico',B1:'Intermediário',B2:'Avançado',C1:'Fluente',C2:'Domínio total'};
const MODULES={
A1:['Primeiros contatos','Alfabeto, números e dados pessoais','Família e pessoas','Rotina diária','Perguntas e hábitos','Casa e cidade','Comida e restaurante','Compras e preços','Direções e transporte','Tempo livre e habilidades','Ontem e fim de semana','Projeto A1: um dia completo em inglês'],
A2:['Rotina em movimento','Histórias do passado','Planos e futuro','Comparando coisas','Viagem e hotel','Saúde e bem-estar','Trabalho e estudo','Experiências de vida','Serviços e problemas','Contando uma história','Vida social','Projeto A2: viagem completa'],
B1:['Experiências e passado','Narrativas mais claras','Futuro e decisões','Condições reais','Conselho e obrigação','Voz passiva básica','Pessoas e coisas','O que alguém disse','Phrasal verbs essenciais','Opiniões e argumentos','Inglês no trabalho e viagem','Projeto B1: conversa de 10 minutos'],
B2:['Tempo e duração','Hipóteses','Desejos e arrependimentos','Passiva avançada','Relato e interpretação','Dedução e probabilidade','Conectando ideias','Expressões naturais','Comunicação profissional','Notícias e mídia','Debate e persuasão','Projeto B2: apresentação e debate'],
C1:['Nuances de tempo e aspecto','Ênfase e inversão','Modalidade avançada','Registro e nominalização','Colocações e idiomaticidade','Escrita profissional e acadêmica','Apresentações de alto nível','Debate e pensamento crítico','Inglês social e humor','Inglês profissional avançado','Escuta rápida e sotaques','Projeto C1: painel profissional'],
C2:['Precisão e escolha de registro','Modalidade e posicionamento','Retórica e persuasão','Linguagem figurada','Idiomaticidade profunda','Argumentação complexa','Edição e precisão','Mediação e paráfrase','Velocidade, sotaques e ruído','Cultura, humor e pragmática','Domínio profissional','Projeto C2: domínio total']};
const LESSON_TYPES=['Vocabulário e escuta','Gramática em contexto','Frases essenciais','Compreensão auditiva','Leitura e interpretação','Produção escrita','Conversação com IA','Desafio do módulo'];
const SKEY='meuInglesStableV1';
const state=Object.assign({level:'A1',teacher:'media',scenario:'Livre',xp:0,done:{}},JSON.parse(localStorage.getItem(SKEY)||'{}'));
let audioCtx=null,source=null,micReady=false,chatHistory=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(SKEY,JSON.stringify(state));renderTopStats()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function modeLabel(){return state.teacher==='pesada'?'Hard 18+':state.teacher==='media'?'Doideira':'Tranquilo'}
function modeClass(){return state.teacher==='pesada'?'hard':state.teacher==='media'?'doida':''}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));window.scrollTo(0,0);if(id==='course')renderCourse();if(id==='chat')renderChatHeader()}
window.stableShow=show;
function setTeacher(t){state.teacher=t;save();$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===t));$$('.bot').forEach(b=>{b.classList.remove('hard','doida');const c=modeClass();if(c)b.classList.add(c)});$('#modeText').textContent=modeLabel()}
window.setStableTeacher=setTeacher;
function setLevel(l){state.level=l;save();renderCourse();renderTopStats()}
window.setStableLevel=setLevel;
function renderTopStats(){const d=Object.values(state.done||{}).filter(Boolean).length;$('#levelStat').textContent=state.level;$('#xpStat').textContent=state.xp;$('#doneStat').textContent=d;$('#modeText').textContent=modeLabel();const c=modeClass();$$('.bot').forEach(b=>{b.classList.remove('hard','doida');if(c)b.classList.add(c)})}
function doneKey(l,m,n){return `${l}-${m}-${n}`}
function moduleDone(l,m){let n=0;for(let i=0;i<8;i++)if(state.done[doneKey(l,m,i)])n++;return n}
function renderCourse(){
 const root=$('#courseBody');const l=state.level;
 root.innerHTML=`<div class="panel"><div class="levelTabs">${Object.keys(LEVELS).map(x=>`<button class="levelTab ${x===l?'active':''}" onclick="setStableLevel('${x}')">${x} · ${LEVELS[x]}</button>`).join('')}</div><h2 style="margin:16px 0 4px">${l} · ${LEVELS[l]}</h2><p class="muted" style="margin:0">12 módulos · 96 aulas neste nível</p></div>${MODULES[l].map((title,m)=>`<div class="module"><h3>${m+1}. ${esc(title)}</h3><p>8 aulas progressivas com explicação, vocabulário, escuta, prática e conversação.</p><div class="moduleMeta"><span class="tag">${moduleDone(l,m)}/8 concluídas</span><span class="tag">Nível ${l}</span></div><button class="btn primary" onclick="openStableModule('${l}',${m})">Abrir módulo</button></div>`).join('')}`;
}
window.openStableModule=(l,m)=>{state.level=l;save();const title=MODULES[l][m];$('#courseBody').innerHTML=`<div class="top"><button class="back" onclick="renderStableCourse()">‹</button><div><h2 style="margin:0">${esc(title)}</h2><div class="muted">${l} · Módulo ${m+1}</div></div></div><div class="lessonGrid">${LESSON_TYPES.map((t,n)=>`<div class="lessonCard"><h4>${n+1}. ${t} ${state.done[doneKey(l,m,n)]?'✓':''}</h4><p>Aula guiada e prática aplicada ao tema do módulo.</p><button class="btn primary" style="margin-top:10px" onclick="openStableLesson('${l}',${m},${n})">${state.done[doneKey(l,m,n)]?'Revisar':'Começar'}</button></div>`).join('')}</div>`;window.scrollTo(0,0)};
window.renderStableCourse=renderCourse;
function fallbackLesson(l,m,n){const title=MODULES[l][m];return{title:`${LESSON_TYPES[n]} · ${title}`,goal_pt:`Usar inglês de nível ${l} no tema ${title}.`,explanation_pt:`Nesta aula você vai aprender e praticar inglês relacionado a ${title}.`,examples:[{en:'Let’s practice this topic in English.',pt:'Vamos praticar este tema em inglês.'},{en:'I can use this in a real conversation.',pt:'Eu consigo usar isso em uma conversa real.'}],vocabulary:[{en:'hello',pt:'olá'},{en:'practice',pt:'praticar'},{en:'conversation',pt:'conversa'},{en:'English',pt:'inglês'}],practice_steps:['Ouça os exemplos.','Repita em voz alta.','Crie uma frase própria.','Responda ao professor em inglês.'],speaking_prompt_en:'Say one complete sentence about this topic.',speaking_help_pt:'Fale uma frase completa sobre o tema.',model_answer_en:'I can talk about this topic in English.',mini_reading_en:'Practice helps you use English with more confidence.',mini_reading_question_pt:'Qual é a ideia principal?',final_task_pt:'Fale uma frase completa usando o conteúdo desta aula.'}}
async function getLesson(l,m,n){const title=MODULES[l][m];const r=await fetch(COURSE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({level:l,module_title:title,grammar:`gramática adequada ao nível ${l} e ao tema ${title}`,vocabulary:`vocabulário de ${title}`,can_do:`comunicar-se sobre ${title}`,lesson_type:LESSON_TYPES[n],lesson_number:n+1})});if(!r.ok)throw new Error('lesson '+r.status);return r.json()}
window.openStableLesson=async(l,m,n)=>{const root=$('#courseBody');root.innerHTML=`<div class="top"><button class="back" onclick="openStableModule('${l}',${m})">‹</button><h2>Aula ${n+1}</h2></div><div class="panel"><h3>Preparando a aula…</h3><p class="muted">Carregando o conteúdo.</p></div>`;let d;try{d=await getLesson(l,m,n)}catch(e){console.warn(e);d=fallbackLesson(l,m,n)}renderLesson(l,m,n,d)};
function renderLesson(l,m,n,d){$('#courseBody').innerHTML=`<div class="top"><button class="back" onclick="openStableModule('${l}',${m})">‹</button><h2>${l} · Aula ${n+1}</h2></div><div class="panel"><h2 style="margin-top:0">${esc(d.title||LESSON_TYPES[n])}</h2><p class="muted">${esc(d.goal_pt||'')}</p></div><div class="lessonSection"><h3>📘 Entenda</h3><p>${esc(d.explanation_pt||'')}</p></div><div class="lessonSection"><h3>💬 Exemplos</h3>${(d.examples||[]).map(e=>`<div class="example"><b>${esc(e.en)}</b><span>${esc(e.pt)}</span><button class="btn" style="margin-top:9px" onclick="stableSpeakEnglish('${encodeURIComponent(e.en||'')}')">🔊 Ouvir</button></div>`).join('')}</div><div class="lessonSection"><h3>🧠 Vocabulário</h3><p class="muted">Toque em qualquer palavra para ouvir a pronúncia.</p>${(d.vocabulary||[]).map(v=>`<div class="vocab" onclick="stableSpeakEnglish('${encodeURIComponent(v.en||'')}')"><b>${esc(v.en)}</b><span>${esc(v.pt)}</span></div>`).join('')}</div><div class="lessonSection"><h3>✍️ Prática guiada</h3><ol class="steps">${(d.practice_steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div>${d.mini_reading_en?`<div class="lessonSection"><h3>📖 Leitura</h3><div class="example"><b>${esc(d.mini_reading_en)}</b><span>${esc(d.mini_reading_question_pt||'')}</span><button class="btn" style="margin-top:9px" onclick="stableSpeakEnglish('${encodeURIComponent(d.mini_reading_en)}')">🔊 Ouvir leitura</button></div></div>`:''}<div class="lessonSection"><h3>🎙️ Fale com o professor</h3><p><b>${esc(d.speaking_prompt_en||'Speak about this topic.')}</b></p><p class="muted">${esc(d.speaking_help_pt||'Responda em inglês.')}</p><button class="mic" id="lessonMic" onclick="stableLessonMic('${l}',${m},${n},'${encodeURIComponent(d.speaking_prompt_en||'Speak about this topic.')}','${encodeURIComponent(d.model_answer_en||'')}')">🎙️</button><div id="lessonFeedback"></div></div><div class="lessonSection"><h3>🏁 Tarefa final</h3><p>${esc(d.final_task_pt||'Use o conteúdo da aula em uma frase completa.')}</p><button class="btn primary wide" onclick="finishStableLesson('${l}',${m},${n})">✅ Concluir aula</button></div>`;window.scrollTo(0,0)}
window.finishStableLesson=(l,m,n)=>{if(!state.done[doneKey(l,m,n)]){state.done[doneKey(l,m,n)]=true;state.xp+=20;save()}window.openStableModule(l,m)};
function recognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang='en-US';r.interimResults=false;r.continuous=false;r.maxAlternatives=5;return r}
async function ensureMic(){if(micReady)return true;if(!navigator.mediaDevices?.getUserMedia)return false;try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());micReady=true;return true}catch(e){return false}}
async function listen(){if(!await ensureMic())throw new Error('mic permission');const r=recognition();if(!r)throw new Error('recognition');return r}
async function askAI(payload){const r=await fetch(CHAT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('AI '+r.status);return r.json()}
window.stableLessonMic=async(l,m,n,qEnc,modelEnc)=>{const box=$('#lessonFeedback'),btn=$('#lessonMic');let r;try{r=await listen()}catch(e){box.innerHTML='<div class="feedback">Não consegui acessar o microfone. Confira a permissão do Chrome.</div>';return}btn.classList.add('listening');box.innerHTML='<div class="feedback">🎧 Estou ouvindo…</div>';r.onresult=async e=>{const heard=e.results[0][0].transcript;btn.classList.remove('listening');box.innerHTML='<div class="feedback">🧠 Analisando sua resposta…</div>';try{const d=await askAI({mode:'conversation',message:`Pergunta da aula: ${decodeURIComponent(qEnc)}\nResposta do aluno: ${heard}\nResposta modelo: ${decodeURIComponent(modelEnc)}`,level:l,personality:state.teacher,scenario:`Curso ${l}: ${MODULES[l][m]}`});box.innerHTML=`<div class="feedback"><b>Você disse:</b> ${esc(heard)}<br><br><b>Professor:</b> ${esc(d.reply_pt||'')}${d.reply_en?`<br><span class="muted">${esc(d.reply_en)}</span>`:''}</div>`;await speakBoth(d.reply_pt||'',d.reply_en||'')}catch(err){box.innerHTML='<div class="feedback">A IA não respondeu agora. Tente novamente em alguns segundos.</div>'}};r.onerror=()=>{btn.classList.remove('listening');box.innerHTML='<div class="feedback">Não consegui entender. Tente novamente.</div>'};r.start()};
function renderChatHeader(){const bot=$('#chatBot');bot.className='bot '+modeClass();$('#chatMode').textContent=modeLabel();$$('[data-chat-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.chatScenario===state.scenario))}
window.setStableScenario=s=>{state.scenario=s;save();renderChatHeader()};
function addMsg(text,who){const d=document.createElement('div');d.className='msg '+(who==='user'?'user':'botmsg');d.textContent=text;$('#chatBox').appendChild(d);$('#chatBox').scrollTop=999999}
window.stableChatMic=async()=>{let r;try{r=await listen()}catch(e){addMsg('Não consegui acessar o microfone.','bot');return}const bot=$('#chatBot'),mic=$('#chatMic');bot.classList.add('listening');mic.classList.add('listening');r.onresult=async e=>{const text=e.results[0][0].transcript;addMsg(text,'user');bot.classList.remove('listening');bot.classList.add('thinking');try{const d=await askAI({mode:'conversation',message:text,level:state.level,personality:state.teacher,scenario:state.scenario,history:chatHistory.slice(-8)});chatHistory.push({role:'user',content:text},{role:'assistant',content:(d.reply_pt||'')+' '+(d.reply_en||'')});const reply=[d.reply_pt,d.reply_en].filter(Boolean).join(' • ');addMsg(reply,'bot');bot.classList.remove('thinking');await speakBoth(d.reply_pt||'',d.reply_en||'')}catch(err){bot.classList.remove('thinking');addMsg('A IA não respondeu agora. Tente novamente em alguns segundos.','bot')}};r.onerror=()=>{bot.classList.remove('listening');addMsg('Não consegui entender. Tente novamente.','bot')};r.onend=()=>mic.classList.remove('listening');r.start()};
function bytes(b64){const bin=atob(b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u}
async function playPCM(b64,rate=24000){const u=bytes(b64),samples=Math.floor(u.length/2),arr=new Float32Array(samples),v=new DataView(u.buffer,u.byteOffset,u.byteLength);for(let i=0;i<samples;i++)arr[i]=Math.max(-1,Math.min(1,v.getInt16(i*2,true)/32768));audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')await audioCtx.resume();if(source){try{source.stop()}catch(e){}}const buf=audioCtx.createBuffer(1,arr.length,rate);buf.copyToChannel(arr,0);source=audioCtx.createBufferSource();source.buffer=buf;source.connect(audioCtx.destination);await new Promise(res=>{source.onended=()=>{source=null;res()};source.start()})}
async function speakTTS(text,lang){text=String(text||'').trim();if(!text)return false;try{const r=await fetch(TTS,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,lang,voice:'Kore',style:lang.startsWith('pt')?'Voz brasileira natural, calorosa e conversacional.':'Natural English teaching voice, clear and friendly.'})});if(!r.ok)throw new Error('tts');const d=await r.json();if(!d.audio)throw new Error('audio');$$('.bot').forEach(b=>b.classList.add('speaking'));await playPCM(d.audio,d.sample_rate||24000);$$('.bot').forEach(b=>b.classList.remove('speaking'));return true}catch(e){return false}}
function browserSpeak(text,lang){return new Promise(res=>{try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=lang.startsWith('en')?.88:1;u.onstart=()=>$$('.bot').forEach(b=>b.classList.add('speaking'));u.onend=()=>{$$('.bot').forEach(b=>b.classList.remove('speaking'));res()};speechSynthesis.speak(u)}catch(e){res()}})}
async function speak(text,lang){if(!await speakTTS(text,lang))await browserSpeak(text,lang)}
window.stableSpeakEnglish=enc=>speak(decodeURIComponent(enc),'en-US');
async function speakBoth(pt,en){if(pt)await speak(pt,'pt-BR');if(en)await speak(en,'en-US')}
async function checkAI(){const badge=$('#aiStatus');try{const r=await fetch(CHAT,{cache:'no-store'}),d=await r.json();if(r.ok&&d.ok&&d.key_configured){badge.className='status ok';badge.textContent='🧠 IA online e pronta';return}throw new Error()}catch(e){badge.className='status bad';badge.textContent='⚠️ IA temporariamente indisponível'}}
async function cleanupOld(){try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const names=await caches.keys();await Promise.all(names.map(n=>caches.delete(n)))}}catch(e){}}
function init(){cleanupOld();renderTopStats();setTeacher(state.teacher);renderCourse();renderChatHeader();checkAI();setInterval(checkAI,45000);$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.screen));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();